### ISSUE TITLE
403 (unauthorized) with authorized account

### ISSUE THREAD

**Issue by shayanb** [censys/censys-python#21]
I'm trying to use the example code for the sdk with the api-key and secret I got on my profile on censys.io. however I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    res = c.new_job("select count(*) from certificates.certificates")
  File "/venv/lib/python2.7/site-packages/censys/query.py", line 13, in new_job
    return self._post("query", data=data)
  File "/venv/lib/python2.7/site-packages/censys/base.py", line 111, in _post
    return self._make_call(self._session.post, endpoint, args, data)
  File "/venv/lib/python2.7/site-packages/censys/base.py", line 105, in _make_call
    const=const)
censys.base.CensysUnauthorizedException: 403 (unauthorized): Unauthorized. You do not have access to this service.
```

**Comment by shayanb** [comment]
It actually worked for the direct API urls using this code:

```
	import sys
	import json
	import requests

	API_URL = "https://www.censys.io/api/v1"
	UID = "_UID_"
	SECRET = "_SECRET_"

	res = requests.get(API_URL + "/data", auth=(UID, SECRET))
	if res.status_code != 200:
	    print "error occurred: %s" % res.json()["error"]
	    sys.exit(1)
	for name, series in res.json()["raw_series"].iteritems():
	    print series["name"], "was last updated at", series["latest_result"]["timestamp"]
```
