### ISSUE TITLE
Exception : Only the first 1,000 search results are available   through the Censys search interface

### ISSUE THREAD

**Issue by abuvanth** [censys/censys-python#30]
I got the exception

Enter the domain:apache.org
[+] Finding the subdomains of apache.org 
Traceback (most recent call last):
  File "censysearch.py", line 48, in <module>
    main(domain,censys_id,censys_secret)
  File "censysearch.py", line 40, in main
    subdomains = subdomain_find(domain,censys_id,censys_secret)
  File "censysearch.py", line 16, in subdomain_find
    for s in cert_search_results:
  File "/usr/local/lib/python2.7/site-packages/censys/base.py", line 172, in search
    payload = self._post(self.search_path, data=data)
  File "/usr/local/lib/python2.7/site-packages/censys/base.py", line 117, in _post
    return self._make_call(self._session.post, endpoint, args, data)
  File "/usr/local/lib/python2.7/site-packages/censys/base.py", line 111, in _make_call
    const=const)
censys.CensysException: 400 (max_results): Only the first 1,000 search results are available 
        through the Censys search interface. Please 
        <a href="/account/billing">upgrade your Censys account</a> or contact 
        <a href="mailto:support@censys.io">support@censys.io</a>.

**Comment by jdonsec** [comment]
@abuvanth Were you able to fix this?
I'm getting the same error.

**Comment by kp625544** [comment]
any update on this?

**Comment by thehappydinoa** [comment]
@kp625544 Could you send the output of the following command as well as information about your current system?

```sh
pip show censys
```
