### ISSUE TITLE
`setup.py` depends in censys package

### ISSUE THREAD

**Issue by marc-etienne** [censys/censys-python#32]
Hi,

I was trying to install `censys` on Windows and the following error:

```
> python -mpip install censys
Collecting censys
  Downloading censys-0.0.8.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
      command: 'C:\%SOME_PATH%\Python\Python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\%USER%\\AppData\\Local\\Temp\\pip-install-k9vn638_\\censys\\setup.py'"'"'; __file__='"'"'C:\\Users\\%USER%\\AppData\\Local\\Temp\\pip-install-k9vn638_\\censys\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\%USER%\AppData\Local\Temp\pip-install-k9vn638_\censys\pip-egg-info'
        cwd: C:\Users\%USER%\AppData\Local\Temp\pip-install-k9vn638_\censys\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\%USER%\AppData\Local\Temp\pip-install-k9vn638_\censys\setup.py", line 4, in <module>
        import censys
    ModuleNotFoundError: No module named 'censys'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is using Windows embedded Python 3.7.7 with pip 20.0.2. Since the cwd is the censys package it should be in `sys.path` but it doesn't seem the case. Maybe because setup is in in an inline command. I'm not sure if importing the still uninstalled package is recommended.

Install worked fine on macOS.

**Comment by marc-etienne** [comment]
This issue is specific to the embedded Python distribution. It doesn't add the empty string in `sys.path`.

I added to following in `sitecustomize.py`: `import sys; sys.path.insert(0, '')`. This require `import site` in `python37._pth`. As described here: https://dev.to/fpim/setting-up-python-s-windows-embeddable-distribution-properly-1081

See also pypa/pip#6163 about PEP-517 and "import to-be-installed package" support.

Cheers!
